### ISSUE TITLE
Unknown entity: com.github.dcysteine.nesql.sql.Metadata

### ISSUE THREAD

**Issue by harrynull** [D-Cysteine/nesql-exporter#1]
The mod failed to export with the following log

GTNH 2.2.8
nesql-exporter 0.4.3

```
[21:29:41] [Thread-57/INFO]: [CHAT] §cSomething went wrong during export! Please check your logs.
[21:29:41] [Thread-57/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.IllegalArgumentException: Unknown entity: com.github.dcysteine.nesql.sql.Metadata
[21:29:41] [Thread-57/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:759)
[21:29:41] [Thread-57/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:742)
[21:29:41] [Thread-57/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.github.dcysteine.nesql.exporter.main.Exporter.export(Exporter.java:142)
[21:29:41] [Thread-57/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.github.dcysteine.nesql.exporter.main.Exporter.exportReportException(Exporter.java:65)
[21:29:41] [Thread-57/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.Thread.run(Thread.java:750)
```

**Comment by D-Cysteine** [comment]
Hmm, there must be some difference in our Java environment that is causing this. Are you trying this with the jars I uploaded to releases, or with jars that you built from source?

**Comment by D-Cysteine** [comment]
Actually, I think I found the issue. I was using automatic scanning of persistence entities, but it looks like that doesn't always work cross-platform. Try these jars; it should fix the issue.

[fixed-jars.zip](https://github.com/D-Cysteine/nesql-exporter/files/10754904/fixed-jars.zip)

**Comment by harrynull** [comment]
Thank you! I can confirm it works now. Really great work by the way!

**Comment by D-Cysteine** [comment]
Thanks! And thanks for finding this issue!
I'm going to poke around with the fix a bit and see if I can improve it, so it won't get pushed to the repo for a while. Will close this once it's pushed.

**Comment by D-Cysteine** [comment]
I came up with a better fix that works on my computer, but it is different from the original fix, so I can't be sure that it will work for you. If it doesn't, please re-open this!
